name: Earnings_Gaps
channels:
  - conda-forge
dependencies:

  # The Works
  - python
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - tqdm

  # Web Scraping
  - requests
  - beautifulsoup4

  # Finance Data
  - yfinance
  - pandas-datareader
  - alpha_vantage

  # Machine Learning
  - tensorflow
  - tensorflow-hub
  - scikit-learn

  # Secrets
  - python-dotenv